---
version: 2.1

commands:
  s3deploy:
    description: "Deploy to S3"
    parameters:
      to:
        type: string
      cf_distribution_id:
        type: string
    steps:
      - run: |
          aws configure set preview.cloudfront true
      - run: |          
          aws s3 sync ./ s3://<< parameters.to >> \
            --acl public-read --delete \
            --cache-control max-age=31536000 
      - run: |            
          aws cloudfront create-invalidation \
              --distribution-id << parameters.cf_distribution_id >> \
              --paths /\*
jobs:
  deploy_production:
    docker:
      - image: circleci/python:3.6-jessie
    working_directory: ~/deploy
    environment:
      PUBLIC_URL: https://conference.codeyourfuture.io
    steps:
      - checkout   
      - persist_to_workspace:
          root: .
          paths:
            - .       
      - attach_workspace:
          at: .
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - s3deploy:
          to: "conference.codeyourfuture.io"
          cf_distribution_id: "E1Q8KZXZADCAQL"
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy_production:
          context: deployments
          filters:
            branches:
              only:
                - master
